#!/bin/bash

ids=$(ls ../../data/interim/reads | cut -d '_' -f 1 | sort | uniq)

for id in $ids; do
    kneaddata \
    -i ../../data/interim/reads/"$id"_R1.fastq \
    -i ../../data/interim/reads/"$id"_R2.fastq \
    -o ../../data/interim/trimmed \
    -db /public/ahnt/courses/bcb5250/metagenomics_wgs_lab/bowtie2db/hg37dec_v0.1 \
    --trimmomatic /public/ahnt/courses/bcb5250/metagenomics_wgs_lab/Trimmomatic-0.39 \
    -t 4 \
    --trimmomatic-options "SLIDINGWINDOW:4:20 MINLEN:50" \
    --bowtie2-options "--very-sensitive --dovetail" \
    --remove-intermediate-output
done

mkdir -p ../../data/interim/contaminated
mv ../../data/interim/trimmed/*_contam_*.fastq ../../data/interim/contaminated
